---
- Media:
    - Request something:
        icon: seerr.png
        href: http://{{HOMEPAGE_VAR_DOMAIN}}:{{HOMEPAGE_VAR_PORT_SEERR}}
        description: Seerr
        siteMonitor: http://{{HOMEPAGE_VAR_CONTAINER_GATEWAY}}:{{HOMEPAGE_VAR_PORT_SEERR}}
        server: local
        container: {{HOMEPAGE_VAR_CONTAINER_SEERR}}

    - Watch something:
        icon: jellyfin.png
        href: http://{{HOMEPAGE_VAR_DOMAIN}}:{{HOMEPAGE_VAR_PORT_JELLYFIN}}
        description: Jellyfin
        siteMonitor: http://{{HOMEPAGE_VAR_CONTAINER_GATEWAY}}:{{HOMEPAGE_VAR_PORT_JELLYFIN}}
        server: local
        container: {{HOMEPAGE_VAR_CONTAINER_JELLYFIN}}

    - Trakt app:
        icon: trakt.png
        href: https://app.trakt.tv
        description: app.trakt.tv
        #siteMonitor: https://app.trakt.tv

    - Statistics:
        icon: jellystat.png
        href: http://{{HOMEPAGE_VAR_DOMAIN}}:{{HOMEPAGE_VAR_PORT_JELLYSTAT}}
        description: Jellystat
        #  Jellystat exposes hardcoded 3000 port
        siteMonitor: http://{{HOMEPAGE_VAR_CONTAINER_GATEWAY}}:3000
        server: local
        container: {{HOMEPAGE_VAR_CONTAINER_JELLYSTAT}}

- Management & System:
    - Torrents:
        icon: qbittorrent.png
        href: http://{{HOMEPAGE_VAR_DOMAIN}}:{{HOMEPAGE_VAR_PORT_QBIT}}
        description: qBitTorrent
        siteMonitor: http://{{HOMEPAGE_VAR_CONTAINER_GATEWAY}}:{{HOMEPAGE_VAR_PORT_QBIT}}
        showStats: true
        server: local
        container: "{{HOMEPAGE_VAR_CONTAINER_QBITTORRENT}}"
        widget:
          type: qbittorrent
          url: http://{{HOMEPAGE_VAR_CONTAINER_GATEWAY}}:{{HOMEPAGE_VAR_PORT_QBIT}}

    - TV Shows Tracker:
        icon: sonarr.png
        href: http://{{HOMEPAGE_VAR_DOMAIN}}:{{HOMEPAGE_VAR_PORT_SONARR}}
        description: Sonarr
        siteMonitor: http://{{HOMEPAGE_VAR_CONTAINER_GATEWAY}}:{{HOMEPAGE_VAR_PORT_SONARR}}
        server: local
        container: {{HOMEPAGE_VAR_CONTAINER_SONARR}}

    - Movies Tracker:
        icon: radarr.png
        href: http://{{HOMEPAGE_VAR_DOMAIN}}:{{HOMEPAGE_VAR_PORT_RADARR}}
        description: Radarr
        siteMonitor: http://{{HOMEPAGE_VAR_CONTAINER_GATEWAY}}:{{HOMEPAGE_VAR_PORT_RADARR}}
        server: local
        container: {{HOMEPAGE_VAR_CONTAINER_RADARR}}

    - Subtitles Downloader:
        icon: bazarr.png
        href: http://{{HOMEPAGE_VAR_DOMAIN}}:{{HOMEPAGE_VAR_PORT_BAZARR}}
        description: Bazarr
        siteMonitor: http://{{HOMEPAGE_VAR_CONTAINER_GATEWAY}}:{{HOMEPAGE_VAR_PORT_BAZARR}}
        server: local
        container: {{HOMEPAGE_VAR_CONTAINER_BAZARR}}

    - Indexers setup:
        icon: prowlarr.png
        href: http://{{HOMEPAGE_VAR_DOMAIN}}:{{HOMEPAGE_VAR_PORT_PROWLARR}}
        description: Prowlarr
        siteMonitor: http://{{HOMEPAGE_VAR_CONTAINER_GATEWAY}}:{{HOMEPAGE_VAR_PORT_PROWLARR}}
        server: local
        container: {{HOMEPAGE_VAR_CONTAINER_PROWLARR}}

    - System state (WSL2):
        icon: glances.png
        href: http://{{HOMEPAGE_VAR_DOMAIN}}:{{HOMEPAGE_VAR_PORT_GLANCES}}
        description: Glances
        siteMonitor: http://{{HOMEPAGE_VAR_CONTAINER_GLANCES}}:{{HOMEPAGE_VAR_PORT_GLANCES}}
        server: local
        container: {{HOMEPAGE_VAR_CONTAINER_GLANCES}}
