---
- Media:
    - Request something:
        icon: seerr.png
        href: http://master.local:5055
        description: Seerr

    - Watch something:
        icon: jellyfin.png
        href: http://master.local:8096
        description: Jellyfin

    - Track it:
        icon: trakt.png
        href: https://trakt.tv
        description: trakt.tv

    - Trakt app:
        icon: trakt.png
        href: https://app.trakt.tv
        description: app.trakt.tv

    - Statistics:
        icon: jellystat.png
        href: http://master.local:3000
        description: Jellystat

- Management:
    - Torrents:
        icon: qbittorrent.png
        href: http://master.local:8080
        description: qBitTorrent

    - TV Shows Tracker:
        icon: sonarr.png
        href: http://master.local:8989
        description: Sonarr

    - Movies Tracker:
        icon: radarr.png
        href: http://master.local:7878
        description: Radarr

    - Subtitles Downloader:
        icon: bazarr.png
        href: http://master.local:6767
        description: Bazarr

    - Indexers setup:
        icon: prowlarr.png
        href: http://master.local:9696
        description: Prowlarr

    - Ads blocking:
        icon: adblock.png
        href: http://master.local:23002
        description: AdGuard
