---
title: Home media center
description: A collection of services to manage and enjoy media library, all running in Docker containers and orchestrated with Docker Compose.
theme: dark
color: slate

background:
  image: /images/current.jpg
  opacity: 30 # 0-100

headerStyle: boxedWidgets
showStats: false
hideVersion: true
hideGroupTitles: true
#cardBlur: xs

clockWeather:
  clockEnabled: {{HOMEPAGE_VAR_CLOCK_ENABLED}}
  clockShowSeconds: {{HOMEPAGE_VAR_CLOCK_SHOW_SECONDS}}
  clockHour12: {{HOMEPAGE_VAR_CLOCK_HOUR12}}
  dateEnabled: {{HOMEPAGE_VAR_DATE_ENABLED}}
  weatherEnabled: {{HOMEPAGE_VAR_WEATHER_ENABLED}}
  weatherCity: "{{HOMEPAGE_VAR_WEATHER_CITY}}"
  weatherUnits: "{{HOMEPAGE_VAR_WEATHER_UNITS}}"
  weatherForecastDays: {{HOMEPAGE_VAR_WEATHER_FORECAST_DAYS}}
  datetimeTimezone: "{{HOMEPAGE_VAR_DATETIME_TIMEZONE}}"
  weatherLatitude: "{{HOMEPAGE_VAR_WEATHER_LATITUDE}}"
  weatherLongitude: "{{HOMEPAGE_VAR_WEATHER_LONGITUDE}}"

disks:
  volumes:
    - mount: /stats/hot
      hostPath: "{{HOMEPAGE_VAR_DISK_STATS_HOT}}"
    - mount: /stats/cold
      hostPath: "{{HOMEPAGE_VAR_DISK_STATS_COLD}}"

layout:
  Media:
    tab: Services
    style: column

  System:
    tab: Services
    style: column

  Personal:
    tab: Bookmarks

  Services:
    tab: Bookmarks

pwa:
  id: /
  icons:
    - src: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/jellyfin.png
      type: image/png
      sizes: 512x512

  screenshots:
    - src: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/jellyfin.png
      sizes: 512x512
      form_factor: wide
      label: Home Media Center - Desktop
    - src: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/jellyfin.png
      sizes: 512x512
      label: Home Media Center - Mobile

  shortcuts:
    - name: Media
      url: "/#Media"
      icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/jellyfin.png
    - name: System
      url: "/#System"
      icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/sonarr.png
    - name: Personal
      url: "/#Personal"
      icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/github.png
    - name: Services
      url: "/#Services"
      icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/router.png
